### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by bradyrussell** [bradyrussell/GunCus#1]
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_181]

**Comment by bradyrussell** [comment]
not fixed by the thread stuff

**Comment by bradyrussell** [comment]
got the entity spawn one done for afaik,
now we have a sound one, i believe we are calling sound packets from the client, causing client crash (not the server anymore tho 💯 )

java.util.ConcurrentModificationException
        at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:401)
        at net.minecraft.client.audio.SoundManager.updateAllSounds(SoundManager.java:272)
        at net.minecraft.client.audio.SoundHandler.update(SoundHandler.java:302)
